name: geocompy
channels:
  - conda-forge
dependencies:
  - bokeh
  - branca
  - cartopy
  - cython
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyter
  - jupyterlab
  - mapclassify
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - proj
  - quarto
  - rasterio
  - rasterstats
  - shapely
  - topojson
