name: geocompy
channels:
  - conda-forge
dependencies:
  - bokeh
  - branca
  # cartopy==0.22.0  
  - cartopy>=0.22
  - cython
  # fiona greater than or equal to 1.9:
  - fiona>=1.9
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyter
  - jupyterlab
  - mapclassify
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - proj
  - quarto
  - rasterio
  - rasterstats
  - shapely
  - topojson
  - osmnx
