name: geocompy
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - cython
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyter
  - jupyterlab
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - proj
  - pygeos
  - rasterio
  - shapely
  - topojson
  - mapclassify
  - rasterstats
  - branca