name: geocompy
channels:
  - conda-forge
#  - default
dependencies:
  - python=3.9
  #- bokeh
  #- cartopy
  #- cython
  #- folium
  #- geopandas
  #- geopy
  #- geoviews
  #- hvplot
  #- jupyter
  #- jupyterlab
  #- matplotlib
  #- nbformat
  #- numpy
  #- pandas
  #- proj
  #- pygeos
  #- rasterio
  #- shapely
  #- topojson
  #- mapclassify
  #- rasterstats
  #- branca
