on:
  push:
    branches:
      [main]
name: Render
jobs:
  bookdown:
    name: conda
    runs-on: ubuntu-latest
    container: geocompr/geocompr:conda
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Render
        run: |
          conda init bash
          conda activate geocompy
          quarto render
          ls docs
          
