on:
  push:
    branches:
      main
name: Convert
jobs:
  bookdown:
    name: Convert
    runs-on: ubuntu-latest
    container: geocompr/geocompr:geocompy
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          pip3 install jupytext
          # Aim: convert .qmd files to .ipynb and .py files, see convert.sh
          for i in *.qmd; do
            quarto convert $i
          done
          jupytext --to py *.ipynb
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit *.ipynb -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
