name: Render-mamba
on: push
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    container: geocompr/geocompr:mamba
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Render
        run: |
          micromamba env list
          ./convert.sh
          ./run-code.sh
          quarto render
          ls docs

