name: PRs
on: pull_request

jobs:
  bookdown:
    name: Test-quarto
    runs-on: ubuntu-latest
    container: ghcr.io/geocompx/docker:python
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          # test code:
          quarto render
          ls docs
