name: PRs
on: pull_request

jobs:
  bookdown:
    name: Test-quarto
    runs-on: ubuntu-latest
    container: geocompr/geocompr:conda
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          conda activate geocompy
          # test code:
          for f in ipynb/*.ipynb; do jupyter nbconvert --execute --to html "$f"; done
          quarto render
          ls docs
